#!/bin/sh

auth="$XDG_DATA_HOME/uncheck/auth"
[ -f $auth ] || { echo "no auth file"; exit; } && bearer=`cat $auth`

usage() {
  echo "usage: uncheck [options] username"
  echo ""
  echo "options:"
  echo "  -h: shows this help message and exits"
  
  exit 1
}

while getopts "h" o; do
  case "$o" in
    h) usage ;;
  esac
done

shift $((OPTIND - 1))

check() {
  api="https://api.twitter.com/2/users/by/username/" 
  err=$(curl -s "$api$1" -H "Authorization: Bearer $bearer" | jq -r '.errors[]? | .detail')
 
  case $err in
    "Could not find user"*) true   ;;
    *)                      false  ;;
  esac
}

notify() {
  notify-send -t 0 uncheck "username $1 available on twitter"
}
