#!/bin/bash

source auth

check() {
  api="https://api.twitter.com/2/users/by/username/" 
  err=$(curl -s "$api$1" -H "Authorization: Bearer $bearer" | jq -r '.errors[]? | .detail')

  [[ $err =~ "Could not find user" ]] && true
}

notify() {
  notify-send -t 0 uncheck "username $1 available on twitter"
}

while true; do
  check $1 && notify $1
  sleep 30m
done
